### ISSUE TITLE
Can you upload a data file?

### ISSUE THREAD

**Issue by breezezero** [kamwoh/concepthash#6]
Dear researcher, can you upload the data file?

**Comment by breezezero** [comment]
Dear researcher, can you upload the data file?

**Comment by kamwoh** [comment]
hi, i will come back to you later

**Comment by kamwoh** [comment]
hi, sorry for late reply, i have uploaded data files and how to prepare them. you may need to download from the original data source

**Comment by breezezero** [comment]
Thank you for your response and for uploading the data files. I appreciate your efforts in making the data available. I will proceed to download the files from the original data source as you suggested.
